name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build
      env:
        PUBLIC_STRAVA_CLIENT_ID: env.PUBLIC_STRAVA_CLIENT_ID
        PUBLIC_SUPABASE_ANON_KEY: env.PUBLIC_SUPABASE_ANON_KEY
        PUBLIC_SUPABASE_URL: env.PUBLIC_SUPABASE_URL
        STRAVA_SECRET: secrets.STRAVA_SECRET

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: build/app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

